name: Deploy YOLO Prod

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      REGION:
        required: true
      BUCKET_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config <<EOF
          Host ec2
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USERNAME }}
            IdentityFile ~/.ssh/private_key
            StrictHostKeyChecking no
          EOF

      - name: Deploy YOLO Container
        run: |
          ssh ec2 <<EOF
          cd ~/YoloService  # update if needed
          git fetch origin
          git reset --hard origin/main

          echo "IMG_NAME=${{ inputs.image }}" > .env

          docker compose -f docker-compose.yolo.prod.yaml pull
          docker compose -f docker-compose.yolo.prod.yaml up -d 
          EOF
