name: Deploy YOLO Dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      EC2_HOST_DEV:
        required: true
      EC2_USERNAME:
        required: true
      REGION:
        required: true
      BUCKET_NAME_DEV:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config <<EOF
          Host ec2
            HostName ${{ secrets.EC2_HOST_DEV }}
            User ${{ secrets.EC2_USERNAME }}
            IdentityFile ~/.ssh/private_key
            StrictHostKeyChecking no
          EOF

      - name: Deploy YOLO Container
        run: |
          ssh ec2 <<EOF
          cd ~/YoloService  # update if needed
          git fetch origin
          git reset --hard origin/dev

          echo "IMG_NAME=${{ inputs.image }}" > .env
          echo "REGION=${{ secrets.REGION }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME_DEV }}" >> .env
          
          
          cat .env  # debug output
          
          docker compose -f docker-compose.yolo.dev.yaml pull
          docker compose -f docker-compose.yolo.dev.yaml up -d 
          EOF
